function love.conf(gameConfig)
  gameConfig.identity = nil                    -- The name of the save directory (string)
  gameConfig.appendidentity = false            -- Search files in source directory before save directory (boolean)
  gameConfig.version = "11.1"                  -- The LÖVE version this game was made for (string)
  gameConfig.console = false                   -- Attach a console (boolean, Windows only)
  gameConfig.accelerometerjoystick = false     -- Enable the accelerometer on iOS and Android by exposing it as a Joystick (boolean)
  gameConfig.externalstorage = false           -- True to save files (and read from the save directory) in external storage on Android (boolean)
  gameConfig.gammacorrect = false              -- Enable gamma-correct rendering, when supported by the system (boolean)

  gameConfig.audio.mixwithsystem = false        -- Keep background music playing when opening LOVE (boolean, iOS and Android only)

  gameConfig.window.title = "Ice Survival War" -- The window title (string)
  gameConfig.window.icon = nil                 -- Filepath to an image to use as the window's icon (string)
  gameConfig.window.width = 1366               -- The window width (number)
  gameConfig.window.height = 768               -- The window height (number)
  gameConfig.window.borderless = true         -- Remove all border visuals from the window (boolean)
  gameConfig.window.resizable = false          -- Let the window be user-resizable (boolean)
  gameConfig.window.minwidth = 1               -- Minimum window width if the window is resizable (number)
  gameConfig.window.minheight = 1              -- Minimum window height if the window is resizable (number)
  gameConfig.window.fullscreen = true          -- Enable fullscreen (boolean)
  gameConfig.window.fullscreentype = "desktop" -- Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
  gameConfig.window.vsync = 0                  -- Vertical sync mode (number)
  gameConfig.window.msaa = 0                   -- The number of samples to use with multi-sampled antialiasing (number)
  gameConfig.window.depth = nil                -- The number of bits per sample in the depth buffer
  gameConfig.window.stencil = nil              -- The number of bits per sample in the stencil buffer
  gameConfig.window.display = 1                -- Index of the monitor to show the window in (number)
  gameConfig.window.highdpi = false            -- Enable high-dpi mode for the window on a Retina display (boolean)
  gameConfig.window.x = nil                    -- The x-coordinate of the window's position in the specified display (number)
  gameConfig.window.y = nil                    -- The y-coordinate of the window's position in the specified display (number)

  gameConfig.modules.audio = true              -- Enable the audio module (boolean)
  gameConfig.modules.data = true               -- Enable the data module (boolean)
  gameConfig.modules.event = true              -- Enable the event module (boolean)
  gameConfig.modules.font = true               -- Enable the font module (boolean)
  gameConfig.modules.graphics = true           -- Enable the graphics module (boolean)
  gameConfig.modules.image = true              -- Enable the image module (boolean)
  gameConfig.modules.joystick = false          -- Enable the joystick module (boolean)
  gameConfig.modules.keyboard = true           -- Enable the keyboard module (boolean)
  gameConfig.modules.math = true               -- Enable the math module (boolean)
  gameConfig.modules.mouse = true              -- Enable the mouse module (boolean)
  gameConfig.modules.physics = true            -- Enable the physics module (boolean)
  gameConfig.modules.sound = true              -- Enable the sound module (boolean)
  gameConfig.modules.system = true             -- Enable the system module (boolean)
  gameConfig.modules.thread = true             -- Enable the thread module (boolean)
  gameConfig.modules.timer = true              -- Enable the timer module (boolean), Disabling it will result 0 delta time in love.update
  gameConfig.modules.touch = false             -- Enable the touch module (boolean)
  gameConfig.modules.video = false             -- Enable the video module (boolean)
  gameConfig.modules.window = true             -- Enable the window module (boolean)
end
